[package]
name = "test-structreturn"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift-codegen = { workspace = true, features = ["riscv32", "arm64"] }
cranelift-frontend = { workspace = true }
cranelift-module = { workspace = true }
cranelift-jit = { workspace = true }
target-lexicon = { workspace = true }
lp-jit-util = { path = "../../crates/lp-jit-util" }

[features]
default = []
asm = []

