[package]
name = "lp-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
hashbrown = { workspace = true }
lp-glsl-compiler = { path = "../lp-glsl-compiler", default-features = false, features = ["std"] }
log = { version = "0.4", default-features = false }

