[package]
name = "embive-program"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "embive-program"
path = "src/main.rs"
test = false

[dependencies]
runtime-embive = { path = "../../../crates/runtime-embive" }

# Cranelift for runtime JIT - carefully configured for no_std, riscv32 only
cranelift-codegen = { workspace = true, features = ["riscv32"] }
cranelift-frontend = { workspace = true, features = ["core"] }
cranelift-jit = { workspace = true, features = ["core"] }
cranelift-module = { workspace = true, features = ["core"] }
cranelift-control = { workspace = true }
target-lexicon = { workspace = true }
hashbrown = { workspace = true }

[build-dependencies]

[target.riscv32imac-unknown-none-elf]


