[package]
name = "runtime-embive"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
test = false

[dependencies]
critical-section = { version = "1.2.0", features = ["restore-state-bool"] }
linked_list_allocator = "0.10"

[target.riscv32imac-unknown-none-elf]


